### ISSUE TITLE
Access R/W issue due to SDCardFS 

### ISSUE THREAD

**Issue by xerta555** [Flex1911/tissot#2]
Hello, I am following the request addressed to you from one of your users [on XDA](https://forum.xda-developers.com/showpost.php?p=75849807&postcount=166).

Being the developer of the [Magisk module "ExSDCard Write Access Enabler"](https://forum.xda-developers.com/apps/magisk/module-exsdcard-write-access-enabler-t3670428), my module is entirely dependent on FUSE to successfully set up an alternative path to the external SD card of the device supported by this kernel.

Off, as you may know, since Oreo, Google has made the decision to implement fully and stably the SDCardFS technology initially created by Samsung, which operates directly at the kernel.
This removal of FUSE technology in favor of SDCardFS has the effect of completely breaking compatibility with my module.

Add to this the obligation to take into account more and more encrypted(s) partition(s), it's very difficult for me, or impossible to change in any way the configuration SDCardFS.
The modification through Magisk of a partition other than that of the already existing system does not work on all phones or all ROMs, i let u imagine the complexity of this type of task.

Ideally, whenever possible, i think it would be good to add to your kernel the possibility to have the configuration switch between SDCardFS and FUSE, by modifying one or more files on the system partitions. (always admitting that it is possible to re-implement the FUSE technology).

If that is possible, i dare to hope that it would not harm the health of the batteries of the devices supported.

You can very well contact me on [XDA](https://forum.xda-developers.com/member.php?u=5332893) and/or here, as u want :+1: 

Have a good day.

**Comment by Flex1911** [comment]
Hi. Since sdcardfs and fuse is something that is being selected on userspace level, there is not so many things that I can do on kernel level. 
On the other side, you can force to disable sdcardfs on userspace level by adding "ro.sys.sdcardfs=false" property.

**Comment by xerta555** [comment]
> Hi. Since sdcardfs and fuse is something that is being selected on userspace level, there is not so many things that I can do on kernel level.
> On the other side, you can force to disable sdcardfs on userspace level by adding "ro.sys.sdcardfs=false" property.

I understand. I have already make some modification to my module to fix this sort of issue.
In the futur, if some users have some issues with R/W sdcard perms, you could link my module, it could help them so.
