### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by wunerrahdev** [Flex1911/tissot#4]
make[1]: Leaving directory '/home/wunerrahdev/android/bliss/out/target/product/tissot/obj/KERNEL_OBJ'
make: *** [Makefile:145: sub-make] Error 2
make: Leaving directory '/home/wunerrahdev/android/bliss/kernel/xiaomi/msm8953'
ninja: build stopped: subcommand failed.
03:14:48 ninja failed with: exit status 1

[0;31m#### failed to build some targets (01:41:58 (hh:mm:ss)) #### [00m

real 102m0.266s
user 282m11.108s
sys 21m19.632s
]0;[arm64-bliss_tissot-userdebug] root@wunerrahdev-HP-Compaq-8000-Elite-CMT-PC: /home/wunerrahdev/android/bliss ]0;root@wunerrahdev-HP-Compaq-8000-Elite-CMT-PC: /home/wunerrahdev/android

**Comment by DEVviL1** [comment]
Are you sure you know how to compile?
Use Google toolchain this isn't going to work with gcc 7.2.1 or simply gcc 7.x!
@Flex1911 close this issue

**Comment by Alann200** [comment]
```Can you describe what you did so you're facing this?```
And which toolchain you using?
I recommend google toolchain for this!
